services:
  db:
    image: postgres:16
    container_name: url_shortener_db
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: url_shortener
    ports:
      - "5433:5432"
    volumes:
      - url_shortener_data:/var/lib/postgresql/data

volumes:
  url_shortener_data:
